services:
  backend:
    build: ./backend
    ports:
      - "4000:4000"

  frontend:
    build: ./frontend
    ports:
      - "4173:4173"
    depends_on:
      - backend
    environment:
      - NODE_ENV=production
      - PORT=4173

networks:
  default:
    ipam:
      config:
        - subnet: 172.20.0.0/24
