services:
    frontend:
        build: ./frontend
        ports:
            - "4173:4173"
        environment:
            - NODE_ENV=production
            - PORT=4173

    backend:
        build: ./backend
